# Generated by Django 3.0.4 on 2024-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetHealthMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnimalName', models.CharField(max_length=500)),
                ('Symptoms_1', models.CharField(max_length=500)),
                ('Symptoms_2', models.CharField(max_length=500)),
                ('Symptoms_3', models.CharField(max_length=500)),
                ('Symptoms_4', models.CharField(max_length=500)),
                ('Symptoms_5', models.CharField(max_length=500)),
                ('Dangerous', models.CharField(max_length=500)),
            ],
        ),
    ]
