# Generated by Django 3.0.4 on 2024-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAdoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_image', models.ImageField(upload_to='Pet')),
                ('pet_name', models.CharField(max_length=400)),
                ('pet_price', models.FloatField()),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=900)),
            ],
        ),
    ]
